packages:
  - apps/*
  - packages/*
  - infra/*
allowBuilds:
  '@clerk/shared': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - tsx@4.22.5
